/*Sqlite3 Query*/
create table SITE_USER_TB(
    SITE_USER_ID INTEGER primary key AUTOINCREMENT,
    SITE_USER_LOGIN_ID TEXT NOT NULL,
    SITE_USER_LOGIN_PW TEXT NOT NULL,
    SITE_USER_DISPLAY_NAME TEXT NOT NULL,
    SITE_USER_EMAIL TEXT NOT NULL,
    SITE_USER_GROUP TEXT NOT NULL
);

create table FORM_DATA_TB(
    FORM_ID INTEGER primary key AUTOINCREMENT,
    FORM_DISPLAY_NAME TEXT NOT NULL,
    FORM_NOTICE_LEVEL TEXT NOT NULL,
    FORM_PUBLISH_DATE NOT NULL,
    FORM_ENABLE INTEGER NOT NULL
)