/*Sqlite3 Query*/
create table SITE_USER_TB(
    SITE_USER_ID INTEGER primary key AUTOINCREMENT,
    SITE_USER_LOGIN_ID TEXT NOT NULL,
    SITE_USER_LOGIN_PW TEXT NOT NULL,
    SITE_USER_DISPLAY_NAME TEXT NOT NULL,
    SITE_USER_EMAIL TEXT NOT NULL,
    SITE_USER_GROUP TEXT NOT NULL
);
create table MEMBER_TB(
    MEMBER_USER_ID INTEGER primary key AUTOINCREMENT,
    MEMBER_USER_DISPLAY_NAME TEXT NOT NULL,
    MEMBER_USER_CLASS INTEGER NOT NULL,
    MEMBER_USER_IS_ENABLED INTEGER NOT NULL
);
create table MEMBER_CONNECT_TB(
    SITE_USER_ID INTEGER NOT NULL,
    MEMBER_USER_ID INTEGER NOT NULL
);
create table MEMBER_DETAIL(
    SITE_USER_ID INTEGER NOT NULL,
    PUBLIC_KEY TEXT NOT NULL,
    PRIVATE_KEY TEXT NOT NULL /* Image Code Directory */
);
create table MEMBER_ATTENDENCE_TB(
    MEMBER_ID INTEGER NOT NULL,
    DATETIME TEXT NOT NULL,
    CHECK_AUTHOR_ID INTEGER NOT NULL
);
create table SEAT_LOCATION_TB(
    TB_ID INTEGER primary key AUTOINCREMENT,
    TB_NAME TEXT NOT NULL
);
